// Quelle: Amtsblatt für Berlin Nr. 41 / 2. Oktober 2025 — "Örtliche Abgrenzung der Wahlkreise
// für die Wahl zum 20. Abgeordnetenhaus von Berlin" (Bekanntmachung vom 24. September 2025)
// Wahltag: 20. September 2026
var WAHLKREISE_DATA = [
{bezirk:"Mitte", anzahl:7, wahlkreise:[
{nr:1, kurz:"Charité, Oranienburger Tor, Zionskirchplatz", grenze:"vom Platz des 18. März in nördlicher Richtung bis zur Spree, der Spree nordwestlich folgend bis Gustav-Heinemann-Brücke, nördlich folgend dem Friedrich-List-Ufer bis zum nördlichen Ende des Humboldthafens, östlich bis Berlin-Spandauer Schifffahrtskanal, diesem nördlich folgend bis Invalidenstraße, südwestlich entlang der Invalidenstraße bis Lesser-Ury-Weg, nordwestlich bis Seydlitzstraße, der Seydlitzstraße in nordöstlicher Richtung folgend bis Lehrter Straße, Lehrter Straße nordwestlich bis Perleberger Straße, nordöstlich bis Nordhafen, diesem südöstlich folgend über die Kieler Brücke bis An der Kieler Brücke, An der Kieler Brücke nordöstlich, später südöstlich folgend bis Boyenstraße, diese nordöstlich bis Chausseestraße, südöstlich folgend der Chausseestraße bis Liesenstraße, nordöstlich bis Gartenstraße, südöstlich bis Theodor-Heuss-Weg, folgend bis Ackerstraße, südöstlich bis Wilhelm-Zermin-Weg, nordöstlich bis Hussitenstraße, südöstlich bis Bernauer Straße, nordöstlich bis zur Bezirksgrenze gegen den Bezirk Pankow, der Bezirksgrenze südöstlich folgend bis Torstraße, Torstraße westlich bis Rosenthaler Platz, Rosenthaler Straße südöstlich folgend bis Sophienstraße, nordwestlich bis Große Hamburger Straße, südlich bis Krausnickstraße, westlich folgend der Krausnickstraße über Oranienburger Straße weiter auf Monbijoustraße bis zur Spree, Spree östlich folgend bis S-Bahn-Strecke, den Gleisen östlich folgend bis Burgstraße, Burgstraße südlich der Spree folgend bis Karl-Liebknecht-Straße, dieser westlich folgend über Unter den Linden bis Platz des 18. März."},
{nr:2, kurz:"Alexanderplatz, Engelbecken, Leipziger Platz", grenze:"vom Platz des 18. März Unter den Linden in östlicher Richtung folgend über Karl-Liebknecht-Straße und Liebknechtbrücke, am Spreeufer nordwestlich weiter auf Burgstraße bis S-Bahn-Strecke, westlich folgend bis Spree, Spree westlich folgend bis Monbijoustraße, nördlich folgend über Oranienburger Straße, übergehend in Krausnickstraße, bis Große Hamburger Straße, nördlich bis Sophienstraße, südöstlich bis Rosenthaler Straße, nord-nordwestlich bis Rosenthaler Platz, Torstraße östlich folgend bis zur Bezirksgrenze gegen Friedrichshain-Kreuzberg, der Bezirksgrenze südlich, westlich und nördlich folgend bis Stresemannstraße, weiter nordwestlich bis Potsdamer Platz, der Ebertstraße folgend bis zum Platz des 18. März."},
{nr:3, kurz:"Südliches Moabit, Hansaviertel, Großer Tiergarten", grenze:"vom Platz des 18. März nördlich bis zur Spree, nordwestlich bis Gustav-Heinemann-Brücke, dem Friedrich-List-Ufer nördlich bis zum nördlichen Ende des Humboldthafens, östlich bis Berlin-Spandauer Schifffahrtskanal, nördlich bis Invalidenstraße, südwestlich bis Lesser-Ury-Weg, nordwestlich bis Seydlitzstraße, südwestlich bis Rathenower Straße, nordwestlich bis Turmstraße, übergehend in Huttenstraße bis Neues Ufer, nördlich bis Sickingenbrücke, westlich bis Bezirksgrenze Charlottenburg-Wilmersdorf, der Bezirksgrenze zu Charlottenburg-Wilmersdorf, Tempelhof-Schöneberg und Friedrichshain-Kreuzberg folgend bis Stresemannstraße, nordwestlich über Ebertstraße bis Platz des 18. März."},
{nr:4, kurz:"Nördliches Moabit, Westhafen", grenze:"vom Nordhafen nordwestlich dem Berlin-Spandauer Schifffahrtskanal folgend bis Föhrer Brücke, nordöstlich über Föhrer/Luxemburger Straße bis Triftstraße, östlich bis Müllerstraße, nordwestlich bis Seestraße, südwestlich bis Schifffahrtskanal, westlich bis Bezirksgrenze Charlottenburg-Wilmersdorf, westlich bis Sickingenbrücke, südlich Neues Ufer, südöstlich Huttenstraße/Turmstraße bis Rathenower Straße, südöstlich bis Seydlitzstraße, nordöstlich bis Lehrter Straße, nordwestlich bis Perleberger Straße, nordöstlich bis Nordhafen."},
{nr:5, kurz:"Schillerpark, Rehberge", grenze:"vom Berlin-Spandauer Schifffahrtskanal an der Bezirksgrenze Charlottenburg-Wilmersdorf nördlich und der Grenze zu Reinickendorf östlich folgend bis Drontheimer Straße, südlich bis Osloer Straße, westlich bis Heinz-Galinski-Straße, südwestlich bis Schulstraße, südwestlich bis Reinickendorfer Straße, nördlich bis Liebenwalder Straße, westlich bis Groninger Straße, südlich bis Utrechter Straße, westlich bis Müllerstraße, nordwestlich bis Seestraße, zurück bis Schifffahrtskanal, westlich bis Bezirksgrenze Charlottenburg-Wilmersdorf."},
{nr:6, kurz:"Soldiner Straße, an der Panke entlang", grenze:"entlang der Bezirksgrenze Pankow Höhe Behmstraße nördlich, westlich, südlich entlang Reinickendorf bis Drontheimer Straße, südlich bis Osloer Straße, westlich bis Heinz-Galinski-Straße, südlich bis Schulstraße, südwestlich bis Reinickendorfer Straße, nördlich bis Liebenwalder Straße, westlich bis Groninger Straße, südlich bis Maxstraße, südöstlich bis Schererstraße, östlich bis Reinickendorfer Straße, südlich bis S-Bahn-Gleise, nordöstlich bis Wiesenstraße, südöstlich bis S-Bahn-Gleise, nordöstlich entlang Hochstraße bis Böttgerstraße, über Behmstraße bis Bezirksgrenze Pankow."},
{nr:7, kurz:"Humboldthain, Nettelbeckplatz", grenze:"von der Bezirksgrenze Pankow Höhe Behmstraße südlich bis Bernauer Straße, westlich bis Hussitenstraße, nordwestlich bis Wilhelm-Zermin-Weg, südwestlich bis Ackerstraße, nordwestlich bis Theodor-Heuss-Weg, südwestlich bis Gartenstraße, nordwestlich bis Liesenstraße, südwestlich bis Chausseestraße, nordwestlich bis Boyenstraße, südwestlich bis An der Kieler Brücke, über die Kieler Brücke bis Nordhafen, dem Schifffahrtskanal nordwestlich bis Föhrer Brücke, nordöstlich über Föhrer/Luxemburger Straße bis Triftstraße, südöstlich bis Müllerstraße, nordwestlich bis Utrechter Straße, nordöstlich bis Maxstraße, südöstlich bis Schererstraße, östlich bis Reinickendorfer Straße, südlich bis S-Bahn-Gleise, nordöstlich bis Wiesenstraße, südöstlich, nordöstlich entlang Hochstraße bis Böttgerstraße, über Behmstraße bis Bezirksgrenze Pankow."}
]},
{bezirk:"Friedrichshain-Kreuzberg", anzahl:5, wahlkreise:[
{nr:1, kurz:"Nördlich Yorckstraße, nördlich Hallesches Ufer/Gitschiner/Skalitzer Straße", grenze:"Wassertorplatz - westlich auf Gitschiner Straße/Hallesches Ufer bis Großbeerenstraße - südlich bis Yorckstraße - südwestlich bis Bezirksgrenze Tempelhof-Schöneberg - westlich entlang Grenze Tempelhof-Schöneberg/Mitte bis zur Spree - südlich entlang Spree bis Oberbaumbrücke - westlich auf Oberbaumstraße/Skalitzer Straße bis Wassertorplatz."},
{nr:2, kurz:"Südlich Yorckstraße, östlich Grimmstraße, südlich Dieffenbachstraße", grenze:"Wassertorplatz - westlich auf Waterloo-Ufer/Tempelhofer Ufer bis Großbeerenstraße - südlich bis Yorckstraße - südwestlich bis Grenze Tempelhof-Schöneberg - südlich bis Grenze Neukölln bis Boppstraße - nordwestlich auf Boppstraße/Schönleinstraße/Dieffenbachstraße bis Grimmstraße - nördlich auf Grimmstraße/Admiralstraße bis Fraenkelufer - westlich auf Fraenkelufer/Erkelenzdamm bis Wassertorplatz."},
{nr:3, kurz:"Südlich Skalitzer Straße, Oberbaumbrücke, Stralauer Halbinsel", grenze:"Wassertorplatz - östlich auf Skalitzer Straße/Oberbaumstraße/Oberbaumbrücke/Warschauer Straße bis Kopernikusstraße - östlich auf Kopernikusstraße/Wühlischstraße bis Boxhagener Straße - östlich bis Grenze Lichtenberg - südlich entlang Grenze Lichtenberg, Treptow-Köpenick, Neukölln bis Boppstraße - nordwestlich bis Grimmstraße - nördlich bis Fraenkelufer - westlich bis Wassertorplatz."},
{nr:4, kurz:"Westlich Warschauer Straße, nördlich der Spree bis Grenze Mitte", grenze:"Frankfurter Tor - südlich auf Warschauer Straße/Am Oberbaum bis zur Spree - nordwestlich entlang Spree bis Grenze Mitte - nördlich entlang Grenze Mitte/Pankow bis Straßmannstraße - westlich bis Petersburger Straße - südlich bis Frankfurter Tor."},
{nr:5, kurz:"Zwischen Warschauer Straße und Grenze Lichtenberg", grenze:"Frankfurter Tor - nördlich auf Petersburger Straße bis Straßmannstraße - östlich bis Grenze Pankow - südlich entlang Grenze Pankow/Lichtenberg bis Boxhagener Straße - westlich auf Boxhagener/Wühlischstraße/Kopernikusstraße bis Warschauer Straße - nördlich bis Frankfurter Tor."}
]},
{bezirk:"Pankow", anzahl:9, wahlkreise:[
{nr:1, kurz:"Buch, Karow, Französisch Buchholz", grenze:"ab nördlicher Landesgrenze Berlin/Brandenburg - östliche Landesgrenze - Ortsteilgrenze Stadtrandsiedlung Malchow - Ortsteilgrenze Blankenburg - Ortsteilgrenze Französisch Buchholz entlang BAB 114 bis Fischteiche - nördlich bis Grenze Anlage Blankenburg - Panke nördlich bis Pankebecken - Nordgraben bis Nisbléstraße - Chartronstraße - Blankenfelder Straße bis Kalvinistenweg - nördlich bis Cunistraße - nordwestlich bis Rosenthaler Weg - nordöstlich bis Mühlenstraße - nordwestlich bis Clementweg - entlang Anlage Am Feldweg bis Krugpfuhlweg - nordwestlich bis Grenzweg - südwestlich bis Straße 124/123 bis Ortsteilgrenze Blankenfelde - B109 Schönerlinder Straße nördlich bis BAB 10 - nordwestlich bis Landesgrenze."},
{nr:2, kurz:"Blankenfelde, Rosenthal, Wilhelmsruh, Niederschönhausen-Nord", grenze:"ab Bezirksgrenze Reinickendorf - Landesgrenze bis BAB A10 - südöstlich bis B109 - Schönerlinder Straße bis Ortsteilgrenze Französisch Buchholz - bis Straße 124 - Grenzweg bis Krugpfuhlweg - entlang Anlage Am Feldweg bis Clémentweg - südöstlich bis Mühlenstraße - Rosenthaler Weg bis Cunistraße - bis Kalvinistenweg - bis Blankenfelder Straße - bis Chartronstraße - Nisbléstraße - bis Ortsteilgrenze Blankenfelde - Anlage Ostsee/Rügen - bis Schönhauser Straße - Buchholzer Straße bis Charlottenstraße - bis Beuthstraße - westlich bis Dietzgenstraße - südlich - Hermann-Hesse-Straße bis Bezirksgrenze Reinickendorf."},
{nr:3, kurz:"Pankow-Nord, Niederschönhausen-Süd, Französisch Buchholz-West", grenze:"ab Bahnbereich Ortsteilgrenze Prenzlauer Berg - westlich bis Bezirksgrenze Mitte/Reinickendorf - nördlich bis Hermann-Hesse-Straße - Dietzgenstraße nördlich bis Beuthstraße - Charlottenstraße südlich bis Buchholzer Straße - nördlich bis Schönhauser Straße - nordwestlich Anlage Rügen/Ostsee bis Ortsteilgrenze Blankenfelde - Nordgraben bis Pankebecken - Panke südlich bis Anlage Blankenburg - Fischteiche bis BAB 114 nördlich bis Grünkardinalweg - Ortsteilgrenze Blankenburg/Heinersdorf bis Heimdallstraße - Bahnbereich bis Ortsteilgrenze Prenzlauer Berg."},
{nr:4, kurz:"Weißensee-Nord, Stadtrandsiedlung Malchow, Blankenburg", grenze:"ab nordöstlicher Landesgrenze - Bezirksgrenze Lichtenberg - Indira-Gandhi-Straße nördlich bis Berliner Allee - westlich bis Pistoriusstraße - Am Steinberg nordöstlich bis Romain-Rolland-Straße - südöstlich bis Wischbergeweg - Malchower Straße westlich bis Wildstrubelpfad - nordöstlich bis Heinersdorfer Graben - Anlage Familiengärten bis Straße 31 - westlich bis Grenze Familiengärten bis Frithjofstraße - Romain-Rolland-Straße nördlich bis Hauptweg - südlich bis Ortsteilgrenze Pankow - BAB 114 nordöstlich bis Ortsteilgrenze Französisch Buchholz/Karow - östliche Landesgrenze."},
{nr:5, kurz:"Pankow-Süd, Heinersdorf", grenze:"ab Bahnbereich Höhe Esplanade nordöstlich bis Berliner Straße - Bahnbereich bis Prenzlauer Promenade nördlich bis Bahnbereich/Ortsteilgrenze Pankow - bis Romain-Rolland-Straße südlich bis Frithjofstraße östlich bis Blankenburger Straße südlich bis Straße 31 - nordöstlich Anlage Familiengärten bis Ortsteilgrenze Blankenburg/Heinersdorfer Graben südöstlich bis Schreckhornweg südwestlich bis Wildstrubelpfad/Malchower Straße östlich bis Wischbergeweg südwestlich bis Romain-Rolland-Straße südwestlich bis Am Steinberg südwestlich bis Prenzlauer Promenade südlich bis Wisbyer Straße - Schönhauser Allee/Mühlenstraße nördlich bis Esplanade."},
{nr:6, kurz:"Esplanade, Schönhauser Allee, Prenzlauer Allee", grenze:"ab Bezirksgrenze Mitte/Eberswalder Straße - Bahnbereich nördlich bis Esplanade - bis Mühlenstraße - Schönhauser Allee bis S-Bahnhof Schönhauser Allee - Bahnbereich bis S-Bahnhof Prenzlauer Allee - südlich bis Danziger Straße - westlich bis Eberswalder Straße - Bezirksgrenze Mitte."},
{nr:7, kurz:"Prenzlauer Berg-West (Wisbyer bis Greifswalder Straße)", grenze:"ab Wisbyer Straße - Prenzlauer Promenade - Am Steinberg - Pistoriusstraße - Berliner Allee südwestlich bis Greifswalder Straße - S-Bahnhof Greifswalder Straße - Bahnbereich nordwestlich bis S-Bahnhof Schönhauser Allee - nördlich bis Wisbyer Straße."},
{nr:8, kurz:"Prenzlauer Berg-Südost (bis Grenze Friedrichshain-Kreuzberg)", grenze:"ab Bezirksgrenze Friedrichshain-Kreuzberg bis Otto-Braun-Straße - Bezirksgrenze Mitte bis Eberswalder Straße - Danziger Straße bis Prenzlauer Allee nördlich bis S-Bahnhof Prenzlauer Allee - Bahnbereich südöstlich bis S-Bahnhof Greifswalder Straße - südwestlich bis Bezirksgrenze Friedrichshain-Kreuzberg."},
{nr:9, kurz:"Weißensee-Südost", grenze:"ab Greifswalder Straße - S-Bahnhof Greifswalder Straße - Berliner Allee - Indira-Gandhi-Straße bis Weißenseer Weg - Bezirksgrenze Lichtenberg - Bezirksgrenze Friedrichshain-Kreuzberg bis Greifswalder Straße."}
]},
{bezirk:"Charlottenburg-Wilmersdorf", anzahl:7, wahlkreise:[
{nr:1, kurz:"Charlottenburg-Nord, Mierendorffplatz, Rathaus", grenze:"von der Mäckeritzbrücke entlang Bezirksgrenze Reinickendorf/Mitte bis zur Spree - östlich bis Gotzkowskybrücke - Franklinstraße - Marchstraße - Fraunhoferstraße - Kohlrauschstraße - Guerickestraße - Cauerstraße - Otto-Suhr-Allee - Luisenplatz - Schloßbrücke - Spree westlich bis Bezirksgrenze Spandau bis Mäckeritzbrücke."},
{nr:2, kurz:"Olympiastadion, Westend, Schloss Charlottenburg, Eichkamp", grenze:"von der S-Bahn-Brücke Ruhlebener Straße entlang Bezirksgrenze Spandau bis Spree - bis Schloßbrücke - Luisenplatz - Spandauer Damm - Klausenerplatz - Danckelmannstraße - Seelingstraße - Sophie-Charlotten-Straße - Knobelsdorffstraße - BAB 100 - Spandauer-Damm-Brücke - Lerschpfad - Crusiusstraße - Königin-Elisabeth-Straße - Haeselerstraße - Soorstraße - Kaiserdamm bis Kaiserdammbrücke - Bahngelände bis Ostpreußenbrücke - Neue Kantstraße - Dernburgstraße - Holtzendorffstraße - Heilbronner Straße - Georg-Wilhelm-Straße - Kurfürstendamm - BAB 100 - Cordesstraße - BAB 115 - Schmetterlingsplatz - Dauerwaldweg - Waldschulallee bis Teufelsseestraße bis Bezirksgrenze Spandau."},
{nr:3, kurz:"Schloßstraße, Lietzensee, Adenauerplatz", grenze:"vom Richard-Wagner-Platz - Schustehrusstraße - Wilmersdorfer Straße - Zillestraße - Sophie-Charlotte-Platz - Kaiserdamm - Windscheidstraße - Schillerstraße - Fritschestraße - Kantstraße - Wilmersdorfer Straße - Krumme Straße - Giesebrechtstraße - Kurfürstendamm - Lehniner Platz - Damaschkestraße - Holtzendorffplatz - Holtzendorffstraße - Dernburgstraße - Neue Kantstraße - Ostpreußenbrücke - Kaiserdammbrücke - Kaiserdamm - Soorstraße - Haeselerstraße - Königin-Elisabeth-Straße - Crusiusstraße - Lerschpfad - Spandauer-Damm-Brücke - BAB 100 - Knobelsdorffstraße - Sophie-Charlotten-Straße - Seelingstraße - Danckelmannstraße - Klausenerplatz - Spandauer Damm - Otto-Suhr-Allee bis Richard-Wagner-Platz."},
{nr:4, kurz:"Deutsche Oper, Ernst-Reuter-Platz, Kurfürstendamm", grenze:"vom Richard-Wagner-Platz - Otto-Suhr-Allee - Cauerstraße - Guerickestraße - Kohlrauschstraße - Fraunhoferstraße - Marchstraße - Franklinstraße - Gotzkowskybrücke - Bezirksgrenze Mitte/Tempelhof-Schöneberg - Nürnberger Straße - Eislebener Straße - Rankestraße - Lietzenburger Straße - Emser Straße - Pariser Straße - Sächsische Straße - Düsseldorfer Straße - Konstanzer Straße - Duisburger Straße - Brandenburgische Straße - Kurfürstendamm - Giesebrechtstraße - Wilmersdorfer Straße - Krumme Straße - Kantstraße - Fritschestraße - Schillerstraße - Windscheidstraße - Kaiserdamm - Sophie-Charlotte-Platz - Zillestraße - Wilmersdorfer Straße - Schustehrusstraße zum Richard-Wagner-Platz."},
{nr:5, kurz:"Grunewaldsee, Halensee, Preußenpark, Hohenzollerndamm", grenze:"von Bezirksgrenze Spandau in der Havel nördlich Am Postfenn bis Teufelsseestraße - Waldschulallee - Sportplätze - Dauerwaldweg - Schmetterlingsplatz - BAB 115 - Cordesstraße - BAB 100 - Kurfürstendamm - Georg-Wilhelm-Straße - Heilbronner Straße - Holtzendorffplatz - Damaschkestraße - Lehniner Platz - Kurfürstendamm - Brandenburgische Straße - Duisburger Straße - Konstanzer Straße - Düsseldorfer Straße - Sächsische Straße - Pommersche Straße - Emser Platz - Hohenzollerndamm - Hundekehlestraße - Schellendorffstraße - Hammersteinstraße - Bernadottestraße bis Bezirksgrenze Steglitz-Zehlendorf/Spandau."},
{nr:6, kurz:"Ludwigkirchplatz, Prager Platz, Bundesplatz, Volkspark", grenze:"von Lietzenburger Straße/Emser Straße - Pariser Straße - Sächsische Straße - Pommersche Straße - Emser Platz - Hohenzollerndamm - Gieselerstraße - Wegenerstraße - Sigmaringer Straße - Brandenburgische Straße - Blissestraße - Am Volkspark - Schrammstraße - Hildegardstraße - Weimarische Straße bis Bezirksgrenze Tempelhof-Schöneberg - Nürnberger Straße - Eislebener Straße - Rankestraße - Lietzenburger Straße bis Emser Straße."},
{nr:7, kurz:"Krematorium Wilmersdorf, Rüdesheimerplatz, Eisstadion Wilmersdorf", grenze:"von Weimarischer Straße entlang Bezirksgrenze Tempelhof-Schöneberg/Steglitz-Zehlendorf - Bernadottestraße - Hammersteinstraße - Schellendorffstraße - Hundekehlestraße - Hohenzollerndamm - Gieselerstraße - Wegenerstraße - Sigmaringer Straße - Brandenburgische Straße - Blissestraße - Am Volkspark - Schrammstraße - Hildegardstraße - Weimarische Straße bis Bezirksgrenze Tempelhof-Schöneberg."}
]},
{bezirk:"Spandau", anzahl:5, wahlkreise:[
{nr:1, kurz:"Hakenfelde, nördliches Falkenhagener Feld, Wasserstadt, nördliche Neustadt", grenze:"von Falkenseer Chaussee entlang Landesgrenze nördlich bis Eiskeller - östlich bis Bezirksgrenze Reinickendorf bis Insel Großer Wall - Havel südlich vorbei an Eiswerder - Eiswerderstraße bis Neuendorfer Straße - nördlich bis Lynarstraße - bis Schönwalder Straße nördlich bis Emdenzeile - Golmer Straße südlich bis Windmühlenberg südlich bis Falkenhagener Straße - westlich über Falkenhagener Tor/Pionierstraße bis Zweibrücker Straße - bis Falkenseer Chaussee westlich bis Am Kiesteich - bis Im Spektefeld bis Beerwinkel nördlich bis Falkenseer Chaussee westlich bis Landesgrenze."},
{nr:2, kurz:"Südliche Neustadt, südöstliches Falkenhagener Feld, Altstadt Spandau, Klosterfelde", grenze:"unterhalb Insel Eiswerder westlich zum Havelufer - Eiswerderstraße bis Neuendorfer Straße nördlich bis Lynarstraße bis Schönwalder Straße nördlich bis Emdenzeile - Golmer Straße bis Windmühlenberg südlich bis Falkenhagener Straße westlich bis Zweibrücker Straße bis Falkenseer Chaussee westlich bis Bahnlinie Bötzowbahn südlich bis Dyrotzer Straße/An der Kappe östlich bis Viersener Straße südlich bis Bahngelände östlich bis Nauener Straße südlich bis Brunsbütteler Damm westlich bis Päwesiner Weg bis Lazarusstraße bis Johannastraße bis Ebersdorfer Straße westlich bis Ulrikenstraße südlich bis Seeburger Weg bis Blasewitzer Ring östlich bis Kleingartenanlage Hasenheide nördlich bis Schmidt-Knobelsdorf-Straße östlich bis Wilhelmstraße nördlich - Klosterstraße bis Bahngelände östlich bis Havel nördlich bis Insel Eiswerder."},
{nr:3, kurz:"Haselhorst, Siemensstadt, Stresow, nordöstliche Wilhelmstadt, Tiefwerder", grenze:"von Bezirksgrenze Reinickendorf Höhe Insel Großer Wall Havel südwärts östlich an Eiswerder vorbei bis Bahngelände westlich bis Klosterstraße südlich über Wilhelmstraße bis Ulmenstraße bis Konkordiastraße südlich bis Adamstraße östlich bis Földerichstraße südlich bis Weverstraße östlich bis Pichelsdorfer Straße südlich bis Genfenbergstraße bis Götelstraße südöstlich zum Havelufer südwärts bis Bezirksgrenze Charlottenburg-Wilmersdorf nördlich bis Bezirksgrenze Reinickendorf westlich bis Insel Großer Wall."},
{nr:4, kurz:"Südwestliches Falkenhagener Feld, Staaken", grenze:"von Landesgrenze entlang Falkenseer Chaussee bis Beerwinkel südlich bis Im Spektefeld östlich bis Am Kiesteich nördlich bis Falkenseer Chaussee östlich bis Bahngelände Bötzowbahn südlich bis Dyrotzer Straße/An der Kappe östlich bis Viersener Straße südlich bis Bahngelände östlich bis Nauener Straße südlich bis Brunsbütteler Damm westlich bis Päwesiner Weg bis Lazarusstraße bis Johannastraße bis Ebersdorfer Straße westlich bis Ulrikenstraße südlich bis Seeburger Weg bis Maulbeerallee westlich bis Kirchengelände St. Maximilian Kolbe bis Gemeinwesenzentrum Heerstraße Nord südlich bis Obstallee westlich bis Magistratsweg südlich bis Heerstraße westlich bis Fort Hahneberg südlich bis Landesgrenze westlich bis Falkenseer Chaussee."},
{nr:5, kurz:"Südliche Wilhelmstadt, Pichelsdorf, Gatow, Kladow", grenze:"von Potsdamer Chaussee/Wilhelmstraße Landesgrenze bis Fort Hahneberg nördlich bis Heerstraße östlich bis Magistratsweg nördlich bis Obstallee östlich bis Gemeinwesenzentrum Heerstraße Nord bis Kirchengelände St. Maximilian Kolbe/Maulbeerallee östlich bis Seeburger Weg/Blasewitzer Ring östlich bis Kleingartenanlage Hasenheide nördlich bis Schmidt-Knobelsdorf-Straße östlich bis Wilhelmstraße nördlich bis Ulmenstraße bis Konkordiastraße südlich bis Adamstraße östlich bis Földerichstraße südlich bis Weverstraße östlich bis Pichelsdorfer Straße südlich bis Genfenbergstraße bis Götelstraße südöstlich zum Havelufer südwärts bis Bezirksgrenze Charlottenburg-Wilmersdorf/Steglitz-Zehlendorf bis Landesgrenze bis Wilhelmstraße."}
]},
{bezirk:"Steglitz-Zehlendorf", anzahl:7, wahlkreise:[
{nr:1, kurz:"Breitenbachplatz, Schloßstraße, Lauenburger Platz, Grunewaldstraße, Asternplatz", grenze:"vom Breitenbachplatz entlang Bezirksgrenze Charlottenburg-Wilmersdorf/Tempelhof-Schöneberg bis Bergstraße westlich bis Bismarckstraße nördlich bis Friedrichsruher Straße westlich bis Schönhauser Straße nördlich bis Kniephofstraße westlich bis Jeverstraße südlich bis Külzer Straße - Bergstraße westlich bis Körnerstraße nördlich bis Joachim-Tiburtius-Brücke - Wannseebahn südlich bis Carmerplatz - Wolfensteindamm bis Hindenburgdamm südlich bis Manteuffelstraße bis Moltkestraße nördlich bis Gardeschützenweg südwestlich bis Tietzenweg nördlich bis Wannseebahn südlich bis Drakestraße nordöstlich bis Habelschwerdter Allee bis Altensteinstraße bis Königin-Luise-Platz - Englerallee nördlich bis Schweinfurthstraße nordwestlich bis Bezirksgrenze Charlottenburg-Wilmersdorf östlich bis Breitenbachplatz."},
{nr:2, kurz:"Albrechtstraße, Steglitzer Damm, Klingsorstraße, Munsterdamm, Halskestraße", grenze:"von östlicher Bezirksgrenze Tempelhof-Schöneberg Höhe Bergstraße südlich bis Teltowkanal westlich bis Krahmerstraße bis Hindenburgdamm nördlich bis Moltkestraße bis Dürerstraße nördlich bis Hindenburgdamm nördlich bis Wolfensteindamm bis Carmerplatz - Wannseebahn nördlich bis Joachim-Tiburtius-Brücke - Körnerstraße südlich bis Bergstraße östlich bis Külzer Straße - Jeverstraße bis Kniephofstraße östlich bis Schönhauser Straße südlich bis Friedrichsruher Straße östlich bis Bismarckstraße südlich bis Bergstraße östlich bis Bezirksgrenze Tempelhof-Schöneberg."},
{nr:3, kurz:"Augustaplatz, Finkensteinallee, Goerzallee, Dahlemer Weg, Teltower Damm, Sachtlebenstraße", grenze:"von südlicher Stadtgrenze Teltowkanal Höhe Am Stichkanal westlich bis Machnower Straße nördlich bis Camphausenstraße südlich bis Gimpelsteig östlich bis Biesestraße bis Schädestraße östlich bis Teltower Damm nördlich bis Mühlenstraße östlich bis Hochbaumstraße bis Dahlemer Weg nördlich bis Unter den Eichen nordöstlich bis Drakestraße südlich bis Wannseebahn nordöstlich bis Tietzenweg südlich bis Gardeschützenweg nordöstlich bis Moltkestraße südlich bis Manteuffelstraße nordöstlich bis Hindenburgdamm südlich bis Dürerstraße bis Moltkestraße südlich bis Hindenburgdamm südlich bis Stockweg westlich bis Lukas-Cranach-Straße bis Tietzenweg nordwestlich bis Dürerstraße südwestlich bis Drakestraße südlich bis Karwendelstraße südöstlich bis Finckensteinallee westlich bis Theklastraße südlich bis Altdorfer Straße westlich bis Marie-Vögtlin-Weg südlich bis Lausanner Straße westlich bis Thuner Straße südlich bis Thuner Platz südöstlich, westlich bis Luzerner Straße westlich bis Osteweg südwestlich bis Platz des 4. Juli südöstlich bis Goerzallee südwestlich bis Am Stichkanal südlich bis Stadtgrenze Teltowkanal."},
{nr:4, kurz:"Hildburghauser Straße, Oberhofer Platz, Thermometersiedlung, Lippstädter Straße", grenze:"von südlicher Stadtgrenze Höhe Ostpreußendamm nördlich bis Teltowkanal südwestlich bis Am Stichkanal nordwestlich bis Goerzallee nordöstlich bis Platz des 4. Juli nordwestlich bis Osteweg nordöstlich bis Luzerner Straße bis Thuner Platz östlich, nördlich bis Thuner Straße nördlich bis Lausanner Straße östlich bis Marie-Vögtlin-Weg nördlich bis Altdorfer Straße östlich bis Theklastraße nördlich bis Finckensteinallee nordöstlich bis Drakestraße nordwestlich bis Dürerstraße nordöstlich bis Tietzenweg südöstlich bis Lukas-Cranach-Straße nordöstlich bis Stockweg südöstlich bis Hindenburgdamm - Krahmerstraße östlich bis Teltowkanal südlich bis Bäkestraße östlich bis Ostpreußendamm südlich bis Bahnhofstraße östlich bis Anhalterbahn nördlich bis Güterbahnhof Lichterfelde Ost bis Elisabethstraße bis Annastraße südlich bis Kaiser-Wilhelm-Straße nordöstlich bis Brigittenstraße südöstlich bis Ingridpfad südwestlich bis Seydlitzstraße südlich bis Derfflingerstraße bis Zietenstraße südlich bis Dessauerstraße westlich bis Kurfürstenstraße südlich bis Geraer Straße östlich bis Sondershauser Straße südlich bis Apoldaer Straße östlich bis Wernshauser Straße südlich bis Wasunger Weg westlich bis Arnstädter Straße südlich bis Hildburghauser Straße östlich bis Bezirksgrenze Tempelhof-Schöneberg südlich bis südlicher Stadtgrenze westlich bis Ostpreußendamm."},
{nr:5, kurz:"Leonorenstraße, Paul-Schneider-Straße, Kamenzer Damm, Gallwitzallee, Siemensstraße, Marienplatz", grenze:"von östlicher Bezirksgrenze Tempelhof-Schöneberg am Teltowkanal Höhe Kolonie Lankwitz Hafen südlich bis Hildburghauser Straße westlich bis Arnstädter Straße nördlich bis Wasunger Straße östlich bis Wernshauser Straße nördlich bis Apoldaer Straße bis Sondershauser Straße nördlich bis Geraer Straße bis Kurfürstenstraße nördlich bis Dessauerstraße östlich bis Zietenstraße bis Derfflingerstraße östlich bis Seydlitzstraße nördlich bis Ingridpfad bis Brigittenstraße bis Kaiser-Wilhelm-Straße südwestlich bis Annastraße nördlich bis Elisabethstraße westlich bis Güterbahnhof Lichterfelde Ost - Anhalterbahn südlich bis Bahnhofstraße - Ostpreußendamm nördlich bis Bäkestraße bis Teltowkanal nordöstlich bis Bezirksgrenze Tempelhof-Schöneberg."},
{nr:6, kurz:"Clayallee, Thielallee, Pacelliallee, Königin-Luise-Straße, Schützallee, Onkel-Tom-Straße", grenze:"von nördlicher Bezirksgrenze Charlottenburg-Wilmersdorf Höhe BAB 115 (AVUS) östlich bis Schweinfurthstraße südlich bis Englerallee südlich bis Königin-Luise-Platz - Altensteinstraße südlich bis Habelschwerdter Allee südlich bis Unter den Eichen südwestlich bis Dahlemer Weg südlich bis Hochbaumstraße westlich bis Teltower Damm südlich bis Schädestraße westlich bis Biesestraße südlich bis Gimpelsteig westlich bis Kamphausenstraße nördlich bis Machnower Straße nördlich bis Schrockstraße nördlich bis Berlepschstraße östlich bis Machnower Straße nördlich bis Teltower Damm nördlich bis Martin-Buber-Straße bis Kirchstraße bis Teltower Damm nördlich bis Potsdamer Straße bis Busseallee bis Beerenstraße bis Glockenstraße bis Sven-Hedin-Straße westlich bis Karl-Hofer-Straße bis Fischerhüttenstraße nordwestlich bis BAB 115 (AVUS) nördlich bis Bezirksgrenze Charlottenburg-Wilmersdorf."},
{nr:7, kurz:"Potsdamer Chaussee, Mexikoplatz, Spanische Allee, Königstraße, Wilhelmplatz, Kohlhasenbrück, Steinstücken", grenze:"von der Glienicker Brücke entlang Stadtgrenze nördlich, entlang Bezirksgrenze Spandau/Charlottenburg-Wilmersdorf bis BAB 115 (AVUS) Höhe Hüttenweg südlich bis Fischerhüttenweg bis Karl-Hofer-Straße südlich bis Sven-Hedin-Straße östlich bis Glockenstraße südlich bis Beerenstraße östlich bis Busseallee südlich bis Potsdamer Straße östlich bis Teltower Damm südlich bis Kirchstraße bis Martin-Buber-Straße bis Teltower Damm südlich bis Machnower Straße bis Berlepschstraße westlich bis Schrockstraße südlich bis Machnower Straße südlich bis südlicher Stadtgrenze westlich bis Glienicker Brücke (mit Steinstücken)."}
]},
{bezirk:"Tempelhof-Schöneberg", anzahl:7, wahlkreise:[
{nr:1, kurz:"Schöneberg-Nord: Wittenbergplatz, Nollendorfplatz, Yorckstraße, Heinrich-von-Kleist-Park, Bayerischer Platz, Viktoria-Luise-Platz", grenze:"von Grunewaldstraße entlang Bezirksgrenzen Charlottenburg-Wilmersdorf, Mitte, Friedrichshain-Kreuzberg bis Monumentenstraße westlich bis Bautzener Straße nördlich bis Hochkirchstraße bis Großgörschenstraße westlich bis Crellestraße südwestlich bis Langenscheidtstraße nordwestlich bis Hauptstraße südlich bis Akazienstraße nördlich bis Apostel-Paulus-Straße westlich bis Eisenacher Straße nördlich bis Grunewaldstraße westlich bis Bezirksgrenze Charlottenburg-Wilmersdorf."},
{nr:2, kurz:"Schöneberg-Süd: Rathaus Schöneberg, Schöneberger Insel, EUREF-Campus, Innsbrucker Platz", grenze:"von Bezirksgrenze Charlottenburg-Wilmersdorf östlich Grunewaldstraße bis Eisenacher Straße südlich bis Apostel-Paulus-Straße östlich bis Akazienstraße südlich bis Hauptstraße nördlich bis Langenscheidtstraße südöstlich bis Willmanndamm östlich bis Crellestraße nördlich bis Großgörschenstraße östlich bis Hochkirchstraße südlich bis Bautzener Straße südlich bis Monumentenstraße östlich bis Bezirksgrenze Friedrichshain-Kreuzberg bis Boelckestraße südlich bis Wüsthoffstraße westlich bis Gontermannstraße südlich bis Werner-Voss-Damm westlich bis S-Bahnhof Südkreuz - Suadicanistraße bis Sachsendamm westlich BAB A100 bis Vorarlberger Damm südwestlich bis Rubensstraße nördlich bis Hauptstraße nordöstlich bis Innsbrucker Platz - S-Bahn-Trasse (Südring) bis Bezirksgrenze Charlottenburg-Wilmersdorf."},
{nr:3, kurz:"Friedenau: S-Bahnhof Friedenau, Lindenhof, Alboinplatz, Marienhöhe, Insulaner", grenze:"von Bezirksgrenze Charlottenburg-Wilmersdorf entlang S-Bahn-Trasse (Südring) bis Innsbrucker Platz südlich bis Rubensstraße südlich bis Vorarlberger Damm östlich bis BAB A100 östlich bis Sachsendamm südöstlich bis Alboinstraße südlich bis Arnulfstraße westlich bis Paul-Schmidt-Straße südlich bis Chlodwigstraße bis Teltowkanal südwestlich bis Bezirksgrenze Steglitz-Zehlendorf nördlich bis S-Bahn-Trasse (Südring)."},
{nr:4, kurz:"Tempelhof: Manfred-v.-Richthofen-Straße, Tempelhofer Park, Teltowkanal, Bosepark, Rathaus Tempelhof", grenze:"Höhe Boelckestraße östlich Bezirksgrenzen Friedrichshain-Kreuzberg/Neukölln bis S-Bahn-Trasse (Südring) westlich bis Gradestraße südlich bis Teltowkanal westlich bis Chlodwigstraße nördlich bis Arnulfstraße östlich bis Alboinstraße nördlich bis Sachsendamm nordwestlich bis Suadicanistraße nördlich bis Werner-Voss-Damm östlich bis Gontermannstraße nördlich bis Wüsthoffstraße östlich bis Boelckestraße nördlich bis Bezirksgrenze Friedrichshain-Kreuzberg."},
{nr:5, kurz:"Mariendorf: Hafen Mariendorf, Ullsteinhaus, Volkspark Mariendorf, Marienpark", grenze:"von Bezirksgrenze Steglitz-Zehlendorf Höhe Teltowkanal nordöstlich bis Gradestraße nördlich bis S-Bahn-Trasse (Südring) bis Bezirksgrenze Neukölln südlich bis Quarzweg westlich bis Ankogelweg nördlich bis Klausenpass westlich bis Mariendorfer Damm nördlich bis Körtingstraße westlich bis Hirzerweg südlich bis Kruckenbergstraße westlich bis Fritz-Werner-Straße südlich bis Wilhelm-von-Siemens-Straße westlich bis Großbeerenstraße südlich bis S-Bahn-Trasse nördlich bis Bezirksgrenze Steglitz-Zehlendorf nördlich bis Teltowkanal."},
{nr:6, kurz:"Marienfelde: S-Bahnhof Marienfelde, Trabrennbahn Mariendorf, Buckower Chaussee, Freizeitpark Marienfelde", grenze:"ab S-Bahn-Trasse Höhe Trachenbergring Bezirksgrenze Steglitz-Zehlendorf südlich bis Marienfelder Allee nördlich bis Großbeerenstraße bis Wilhelm-von-Siemens-Straße östlich bis Fritz-Werner-Straße nördlich bis Kruckenbergstraße östlich bis Hirzerweg nördlich bis Körtingstraße östlich bis Mariendorfer Damm südlich bis Pilatusweg östlich bis Tauernallee südlich bis Quarzweg östlich bis Bezirksgrenze Neukölln südlich bis Buckower Chaussee westlich bis Halker Zeile südlich bis Goethestraße westlich bis Geibelstraße südlich bis Simpsonweg westlich bis Barnetstraße westlich bis Wünsdorfer Straße südlich bis Grenzweg westlich bis Franziusweg südlich bis Maffeistraße westlich bis Illigstraße südlich bis Blohmstraße südöstlich bis Stadtgrenze Teltow-Fläming nordwestlich bis Bezirksgrenze Steglitz-Zehlendorf bis S-Bahn-Trasse Höhe Trachenbergring."},
{nr:7, kurz:"Lichtenrade: Volkspark Lichtenrade, Kirchhainer Damm, S-Bahnhof Lichtenrade", grenze:"von Bezirksgrenze Neukölln Höhe Buckower Chaussee südlich, östlich bis Landesgrenze Dahme-Spreewald südlich, westlich, nordwestlich bis Höhe Blohmstraße westlich bis Illigstraße nördlich bis Maffeistraße östlich bis Franziusweg nördlich bis Grenzweg östlich bis Wünsdorfer Straße nördlich bis Barnetstraße östlich bis Simpsonweg nördlich bis Geibelstraße bis Goethestraße östlich bis Halker Zeile nördlich bis Buckower Chaussee östlich bis Bezirksgrenze Neukölln."}
]},
{bezirk:"Neukölln", anzahl:6, wahlkreise:[
{nr:1, kurz:"Nord-Neukölln (Ost), nördliche Sonnenallee", grenze:"vom Kottbusser Damm/Maybachufer entlang Bezirksgrenze Friedrichshain-Kreuzberg und Treptow-Köpenick (Harzer/Bouchéstraße/Heidelberger/Treptower Straße) bis Kiefholzstraße, südlich entlang S-Bahntrasse bis Sonnenallee, nordwestlich bis Treptower Straße, entlang Donaustraße bis Weichselstraße, südwestlich zur Karl-Marx-Straße, nördlich bis Hermannplatz, nördlich Kottbusser Damm zum Ausgangspunkt."},
{nr:2, kurz:"Nord-Neukölln (West), nördliche Karl-Marx-Straße, nördliche Hermannstraße", grenze:"ab Hasenheide/Lilienthalstraße östlich bis Hermannplatz, südöstlich Karl-Marx-Straße bis Weichselstraße, Donaustraße bis Wanzlikpfad, südlich Kirchgasse/Richardstraße/Richardplatz/Karl-Marx-Platz bis Karl-Marx-Straße südlich bis Bahntrasse westlich Siegfriedstraße bis Bezirksgrenze Tempelhof-Schöneberg, nördlich bis Ausgangspunkt."},
{nr:3, kurz:"Rixdorf, nördliches Britz, Köllnische Heide", grenze:"ab Kiefholzstraße/Bahntrasse südlich Bezirksgrenze Treptow-Köpenick bis Anna-Nemitz-Brücke, westlich Späthstraße/Blaschkoallee/Gradestraße bis Tempelhofer Weg, nordwestlich bis Bezirksgrenze Tempelhof-Schöneberg nördlich bis Siegfriedstraße, östlich bis Karl-Marx-Straße nördlich bis Karl-Marx-Platz, östlich Richardplatz/-straße nördlich Kirchgasse/Wanzlikpfad/Donaustraße/Treptower Straße/Sonnenallee südöstlich bis Bahntrasse Saalestraße, nördlich zum Ausgangspunkt."},
{nr:4, kurz:"Nordöstliches Buckow, Gropiusstadt, nördliches Blumenviertel", grenze:"ab Bezirksgrenze Treptow-Köpenick Anna-Nemitz-Brücke südöstlich Teltowkanal bis Zwergasternweg, südwestlich Minzeweg/Flurweg bis Neuköllner Straße südlich bis Fritz-Erler-Allee, westlich über Agnes-Straub-Weg/Horst-Casper-Steig/Friedrich-Kayßler-Weg/Sollmanweg bis Landesgrenze, Kölner Damm bis Severingstraße nördlich bis Fritz-Erler-Allee/Gutschmidtstraße bis Parchimer Allee bis Buschkrugallee nördlich bis Späthstraße östlich zum Ausgangspunkt."},
{nr:5, kurz:"Südwestliches Britz, südwestliches Buckow", grenze:"ab Tempelhofer Weg/Wilhelm-Borgmann-Brücke südlich Gradestraße östlich Blaschkoallee bis Buschkrugallee südlich Parchimer Allee bis Fritz-Reuter-Allee bis Gutschmidtstraße südlich Grüner Weg/Severingstraße/Kölner Damm bis Landesgrenze westlich bis Bezirksgrenze Tempelhof-Schöneberg Töpchiner Weg nördlich zum Ausgangspunkt."},
{nr:6, kurz:"Rudow, südliches Blumenviertel, südliche Gropiusstadt", grenze:"ab Zwergasternweg/Teltowkanal südlich Bezirksgrenze Treptow-Köpenick bis Landesgrenze Waltersdorfer Chaussee, westlich, nördlich bis Sollmannweg östlich Friedrich-Kayßler-Weg/Horst-Casper-Steig/Agnes-Straub-Weg bis Neuköllner Straße nördlich bis Flurweg nordöstlich Minzeweg zum Ausgangspunkt."}
]},
{bezirk:"Treptow-Köpenick", anzahl:7, wahlkreise:[
{nr:1, kurz:"Alt-Treptow, Plänterwald, Baumschulenweg", grenze:"entlang Bezirksgrenze Friedrichshain-Kreuzberg im Norden, Spree südöstlich bis Britzer Verbindungskanal, westlich bis Bezirksgrenze Neukölln, nördlich bis Bezirksgrenze Friedrichshain-Kreuzberg."},
{nr:2, kurz:"Oberschöneweide, Dammvorstadt, Altstadt Köpenick, Hirschgarten", grenze:"im Norden Bezirksgrenze Lichtenberg bis S-Bahn-Trasse S3, bis östliche Grenze vor Friedrichshagen, Am Wiesenrain/Mühlweg bis Müggelseedamm östlich bis Flussbad Kamerun, Müggelspree/Kietzer Graben, Dahme nördlich bis Spree nordwestlich bis Bezirksgrenze Lichtenberg."},
{nr:3, kurz:"Niederschöneweide, Oberspree, südliches Baumschulenweg, Johannisthal, Adlershof (West)", grenze:"vom Wasserstraßenkreuz Teltowkanal/Britzer Verbindungskanal östlich bis Spree, südöstlich bis Wilhelm-Spindler-Brücke, Spindlersfelder Straße bis Köllnische Brücke, S47 westlich bis Ostritzer Straße südlich bis Oberspreestraße westlich bis Köllnische Heide südwestlich bis Gleisanlage westlich bis Adlergestell südöstlich bis Stelling-Janitzky-Brücke, Teltowkanal nordwestlich zum Ausgangspunkt."},
{nr:4, kurz:"Altglienicke, Bohnsdorf", grenze:"ab A113 östlich Teltowkanal bis S-Bahn/Adlergestell südöstlich bis Kablower Weg südlich Ortsteilgrenze Bohnsdorf bis Landesgrenze Brandenburg westlich bis Bezirksgrenze Neukölln nördlich bis Teltowkanal."},
{nr:5, kurz:"Spindlersfeld, Köllnische Vorstadt, Adlershof (Ost), Grünau, Karolinenhof, Schmöckwitz, Rauchfangswerder", grenze:"ab Adlergestell/S47 östlich Gleisanlage bis Köllnische Heide nordöstlich bis Oberspreestraße östlich bis Ostritzer Straße nördlich bis S47 östlich bis Köllnische Brücke nördlich Spindlersfelder Straße bis Wilhelm-Spindler-Brücke, Spree östlich bis Dahmemündung südlich bis Seddinsee östlich bis Landesgrenze Gosen, Dahme-Spreewald bis Ortsteilgrenze Bohnsdorf nordöstlich bis S-Bahn-Gleisanlage nordwestlich Adlergestell zum Ausgangspunkt."},
{nr:6, kurz:"Allendeviertel, Kietz, Kietzer Feld, Wendenschloß, Müggelheim", grenze:"ab Müggelheimer Straße/Kietzer Graben Amtsstraße bis Landjägerstraße bis Kietzer Graben bis Müggelspree bis Dämeritzsee, Grenze Oder-Spree bis Seddinsee, Dahme nördlich zum Ausgangspunkt."},
{nr:7, kurz:"Köpenick Nord, Friedrichshagen, Rahnsdorf, Wilhelmshagen", grenze:"östlich Bezirksgrenze Lichtenberg/Marzahn-Hellersdorf bis Stadtgrenze, Kreisgrenzen Märkisch-Oderland/Oder-Spree südlich bis Dämeritzsee/Müggelspree westlich über Großen Müggelsee bis Flussbad Kamerun, nördlich bis Müggelseedamm bis Hahns Mühle, nördlich Mühlweg/Am Wiesenrain bis Neuenhagener Mühlenfließ nördlich bis S3 westlich bis Bezirksgrenze Lichtenberg."}
]},
{bezirk:"Marzahn-Hellersdorf", anzahl:6, wahlkreise:[
{nr:1, kurz:"Ahrensfelde-Süd, Marzahn-West, Marzahn-Ost", grenze:"von Bezirksgrenze Lichtenberg/Stadtgrenze östlich, südlich bis Landsberger Allee, Blumberger Damm nördlich bis Lea-Grundig-Straße westlich bis Mehrower Allee, S-Bahn-Trasse S7 nördlich bis Wuhletalstraße westlich bis Wolfener Straße südlich bis Hellersdorfer Weg westlich bis Bezirksgrenze Lichtenberg nördlich zum Ausgangspunkt."},
{nr:2, kurz:"Gewerbegebiet, Marzahner Promenade, Allee der Kosmonauten", grenze:"von Bezirksgrenze Lichtenberg/Hellersdorfer Weg östlich Wolfener Straße nördlich bis Wuhletalstraße östlich bis S7 südlich bis Mehrower Allee östlich Lea-Grundig-Straße südlich bis Blumberger Damm südlich bis Landsberger Allee östlich bis Prötzeler Ring/Trappenfelder Pfad südlich bis Spitzmühler Straße westlich bis Blumberger Damm südlich bis Elisabethstraße westlich bis Allee der Kosmonauten westlich bis Poelchaustraße bis Dahmeweg nördlich bis Landsberger Allee westlich bis Bezirksgrenze Lichtenberg."},
{nr:3, kurz:"Kienberg, Alt-Hellersdorf, Hellersdorf Nord, Hönow-West", grenze:"Stadtgrenze/Landsberger Allee östlich, südlich bis Ortsteilgrenze Hellersdorf-Mahlsdorf südlich bis Riesaer Straße westlich bis U5 südlich bis Feuerwache westlich Jelena-Šantić-Friedenspark bis Wuhle südlich bis Ortsteilgrenze Marzahn-Biesdorf westlich bis Blumberger Damm nördlich bis Spitzmühler Straße östlich bis Trappenfelder Pfad/Prötzeler Ring nördlich bis Landsberger Allee bis Stadtgrenze."},
{nr:4, kurz:"Marzahner Chaussee, Springpfuhl, Biesdorf-Nord, Biesdorf-Süd", grenze:"von Rhinstraße/Landsberger Allee östlich bis S7, Dahmeweg südlich bis Poelchaustraße östlich bis Allee der Kosmonauten östlich bis Elisabethstraße östlich bis Blumberger Damm nördlich bis Ortsteilgrenze Marzahn-Biesdorf östlich bis Wuhle südlich bis Bezirksgrenze Treptow-Köpenick westlich bis Bezirksgrenze Lichtenberg nördlich zur Rhinstraße."},
{nr:5, kurz:"Kaulsdorf-Süd, Mahlsdorf-Nord, Mahlsdorf-Süd", grenze:"vom S-/U-Bahnhof Wuhletal entlang S5 östlich bis Ortsteilgrenze Kaulsdorf-Mahlsdorf nördlich bis Markgrafenstraße/Wernerstraße westlich bis Ernst-Haeckel-Straße nördlich bis Randweg bis Ortsteilgrenze Kaulsdorf-Hellersdorf östlich bis Mahlsdorf-Hellersdorf nördlich bis Stadtgrenze östlich, südlich bis Bezirksgrenze Treptow-Köpenick westlich bis Wuhle nördlich zum Ausgangspunkt."},
{nr:6, kurz:"Kaulsdorf Nord, Hellersdorf Süd", grenze:"vom S-/U-Bahnhof Wuhletal nördlich bis Jelena-Šantić-Friedenspark östlich bis U5 nördlich bis Riesaer Straße östlich bis Ortsteilgrenze Hellersdorf-Mahlsdorf südlich bis Hellersdorf-Kaulsdorf westlich bis Randweg südlich bis Ernst-Haeckel-Straße südlich bis Wernerstraße/Markgrafenstraße östlich bis Ortsteilgrenze Kaulsdorf-Mahlsdorf südlich bis S5 westlich zum Ausgangspunkt."}
]},
{bezirk:"Lichtenberg", anzahl:6, wahlkreise:[
{nr:1, kurz:"Wartenberg, Falkenberg, Neu-Hohenschönhausen (Ost)", grenze:"ab Bahngleise/B2 bis Hechtgraben südwestlich bis Zingster Straße bis Falkenberger Chaussee westlich bis Rüdickenstraße bis Am Breiten Luch bis Rotkamp nordöstlich bis Bahngleise bis S-Bahnhof Gehrenseestraße nordöstlich Bezirksgrenze Marzahn-Hellersdorf/Landesgrenze bis B2."},
{nr:2, kurz:"Malchow, Neu-Hohenschönhausen (West), Alt-Hohenschönhausen bis Sportforum, Konrad-Wolf-Straße", grenze:"ab B2 südlich Bezirksgrenze Pankow bis Indira-Ghandi-Straße/Weißenseer Weg bis Konrad-Wolf-Straße bis Sandinostraße bis Küstriner Straße bis Simon-Bolivar-Straße bis Zechliner Straße bis Genslerstraße bis Plauener Straße bis Joachimsthaler/Biesenthaler Straße bis Arendsweg bis Landsberger Allee bis Bezirksgrenze Marzahn-Hellersdorf bis S-Bahnhof Gehrenseestraße nordwestlich Rotkamp/Am Breiten Luch/Rüdickenstraße/Falkenberger Chaussee/Zingster Straße/Hechtgraben bis B2."},
{nr:3, kurz:"Alt-Hohenschönhausen (Süd), Fennpfuhl, Rosenfelder Ring, Gensinger Straße", grenze:"ab Indira-Ghandi-Straße/Weißenseer Weg Bezirksgrenze Pankow bis Karl-Lade-Straße/Paul-Junius-Straße/Herzbergstraße bis Siegfriedstraße bis Gotlindestraße bis Hagenstraße bis Fanningerstraße bis Guntherstraße bis Gudrunstraße bis Frankfurter Allee/Alt-Friedrichsfelde bis Bezirksgrenze Marzahn-Hellersdorf nördlich bis Landsberger Allee/Rhinstraße westlich bis Arendsweg bis Biesenthaler/Joachimsthaler Straße bis Plauener Straße bis Genslerstraße bis Zechliner/Simon-Bolivar/Küstriner Straße bis Sandinostraße bis Konrad-Wolf-Straße bis Weißenseer Weg bis Bezirksgrenze Pankow."},
{nr:4, kurz:"Südlich Karl-Lade-Straße, Paul-Junius-Straße, Herzbergstraße, Stadtpark, Victoriastadt", grenze:"ab Landsberger Allee/Karl-Lade-Straße Bezirksgrenze Pankow/Friedrichshain-Kreuzberg bis Bahngleise Kynaststraße bis S-Bahnhof Nöldnerplatz/Lichtenberg - Gudrunstraße bis Guntherstraße bis Fanningerstraße bis Hagenstraße bis Gotlindestraße bis Siegfriedstraße bis Herzbergstraße/Paul-Junius/Karl-Lade-Straße bis Bezirksgrenze Pankow."},
{nr:5, kurz:"Friedrichsfelde, Tierpark", grenze:"Bahngleise ab Kynaststraße Richtung Rummelsburg bis Fischerstraße nordöstlich bis Lückstraße/Wönnichstraße - Sewanstraße bis Am Tierpark/Treskowallee bis Richard-Kolkwitz-Weg bis Bezirksgrenze Marzahn-Hellersdorf nördlich bis Alt-Friedrichsfelde bis S-Bahnhof Lichtenberg bis Nöldnerplatz bis Kynaststraße."},
{nr:6, kurz:"Karlshorst, Trabrennbahn, Rummelsburg", grenze:"ab Bezirksgrenze Kynaststraße Friedrichshain-Kreuzberg/Treptow-Köpenick/Marzahn-Hellersdorf bis Richard-Kolkwitz-Weg bis Treskowallee/Am Tierpark bis Sewanstraße/Lückstraße bis Wönnichstraße südlich bis Fischerstraße südöstlich bis Bahngleise nordwestlich bis Kynaststraße."}
]},
{bezirk:"Reinickendorf", anzahl:6, wahlkreise:[
{nr:1, kurz:"Reinickendorf-Ost, Reinickendorf-West (teilweise)", grenze:"von Roedernallee/Am Nordgraben östlich bis S-Bahn-Gleise/Grenze Pankow südöstlich bis Panke südlich bis Kühnemannstraße/Nordbahnstraße westlich Grenze Mitte bis Provinzstraße südlich bis Ritterlandweg westlich bis Reginhardstraße südwestlich Grenze Mitte bis Markstraße nördlich bis Walderseestraße westlich bis Brienzer Straße nördlich bis Holländerstraße westlich bis Teichstraße nördlich bis Gotthardstraße westlich bis Brusebergstraße nördlich bis Humboldtstraße nordöstlich bis Lindauer Allee östlich bis Roedernallee nördlich bis S-Bahn-Brücke westlich bis Thyssenstraße nordöstlich bis Roedernallee bis Am Nordgraben."},
{nr:2, kurz:"Reinickendorf-West, Tegel-Süd (teilweise), Wittenau (teilweise), Mäckeritzwiesen", grenze:"von Rathauspromenade/Am Nordgraben östlich bis Roedernallee südlich bis Thyssenstraße südwestlich S-Bahn-Gleise östlich bis Roedernallee südlich bis Lindauer Allee/Humboldtstraße südwestlich bis Brusebergstraße südlich bis Gotthardstraße östlich bis Teichstraße südlich bis Holländerstraße westlich Grenze Mitte über Kapweg bis Kurt-Schumacher-Damm bis Hinckeldeybrücke, Hohenzollernkanal Grenze Charlottenburg-Wilmersdorf westlich bis Bernauer Straße nördlich, östlich bis Bernhard-Lichtenberg-Platz - Berliner Straße nördlich bis Ernststraße östlich bis S-Bahn-Gleise bis Oranienburger Straße nördlich bis Rathauspromenade."},
{nr:3, kurz:"Heiligensee, Konradshöhe, Tegelort, Tegel (teilweise), Tegel-Süd (teilweise), Saatwinkel", grenze:"vom nördlichen Ufer Niederneuendorfer See östlich Landesgrenze, Ortsteilgrenze Heiligensee/Frohnau bis Ende Tegeler Forst/Grenze Tegel-Hermsdorf südlich bis Tegeler Fließ westlich bis S-Bahn-Trasse südlich bis Waidmannsluster Damm westlich bis Karolinenstraße südlich bis Berliner Straße südlich bis Bernhard-Lichtenberg-Platz - Bernauer Straße westlich, südlich bis Hohenzollernkanal Grenze Spandau nördlich bis Havel nördlich bis Landesgrenze bis Niederneuendorfer See."},
{nr:4, kurz:"Wittenau (teilweise), Waidmannslust, Borsigwalde, Tegel (teilweise)", grenze:"von Berliner Straße/Waidmannsluster Damm nordöstlich bis Hochjagdstraße südöstlich bis Packereigraben nordöstlich bis S-Bahn-Trasse nordwestlich über Dianastraße bis Tegeler Fließ flussaufwärts bis Hermsdorfer See südwärts Büchenbronner Steig/Ziegeleigraben/Erlenbruchgraben bis Öschelbronner Weg/Welzower Steig bis Kolonie Seggeluchbecken östlich bis Finsterwalder Straße südlich, südwestlich bis S-Bahn-Linie südöstlich bis Schorfheidestraße/Am Nordgraben westlich bis Rathauspromenade südlich, östlich bis Oranienburger Straße südlich bis Ernststraße westlich bis Berliner Straße nördlich bis Waidmannsluster Damm."},
{nr:5, kurz:"Lübars, Märkisches Viertel", grenze:"vom Tegeler Fließ Landesgrenze östlich, südlich Grenze Pankow bis S-Bahn-Linie/Am Nordgraben westlich bis S-Bahnhof Wilhelmsruher Damm nordöstlich bis Finsterwalder Straße bis Kolonie Frohsinn westlich bis Welzower Steig nördlich bis Öschelbronner Weg nördlich Erlenbruchgraben/Ziegeleigraben/Büchenbronner Steig bis Hermsdorfer See/Tegeler Fließ nordöstlich bis Landesgrenze."},
{nr:6, kurz:"Frohnau, Hermsdorf, Freie Scholle", grenze:"von Ortsteilgrenze Heiligensee/Frohnau Landesgrenze nordöstlich, östlich, südlich, südöstlich bis Ortsteilgrenze Hermsdorf/Lübars - Tegeler Fließ südwestlich über Oraniendamm bis S-Bahn-Trasse bis Packereigraben westlich bis Avenue Charles de Gaulle nördlich bis Waidmannsluster Damm südwestlich bis Hermsdorfer Damm nördlich bis Tegeler Fließ nördlich bis Ortsteilgrenze Hermsdorf/Tegel nördlich bis Ortsteilgrenze Frohnau/Tegel westlich bis Landesgrenze/Ortsteilgrenze Heiligensee/Frohnau."}
]}
];

// Hilfsfunktion: alle Wahlkreise als flache Liste (für Suche)
function alleWahlkreiseFlat() {
  var out = [];
  WAHLKREISE_DATA.forEach(function(b) {
    b.wahlkreise.forEach(function(w) {
      out.push({ bezirk: b.bezirk, nr: w.nr, kurz: w.kurz, grenze: w.grenze });
    });
  });
  return out;
}
